server:
  port: 9091
spring:
  application:
    name: api-gateway
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:9090/eureka
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
  SocketTimeout: 10000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000
management:
  endpoints:
    web:
      exposure:
        include:  '*'
  metrics:
    tags:
      application: ${spring.application.name}
