apiVersion: v1
data:
  application.yml: "server:\r\n  port: 10001\r\nspring:\r\n  application:\r\n    name:
    first-server\r\n  cloud:\r\n    loadbalancer:\r\n      retry:\r\n        enabled:
    true\r\neureka:\r\n  client:\r\n    serviceUrl:\r\n      defaultZone: http://192.168.126.135:30001/eureka\r\n
    \ instance:\r\n    prefer-ip-address: true\r\n    instance-id: ${spring.application.name}:${server.port}\r\nswagger:\r\n
    \ ui:\r\n    title: first-service接口Api文档\r\n    description: Wsg层暴露Api\r\n    termsOfServiceUrl:
    http://www.si-tech.com.cn\r\n    contact:\r\n      name: wanpp\r\n      url:\r\n
    \     email: wanpp@si-tech.com.cn\r\n    version: 1.0\r\nmanagement:\r\n  endpoints:\r\n
    \   web:\r\n      exposure:\r\n        include:  '*'\r\n  metrics:\r\n    tags:\r\n
    \     application: ${spring.application.name}\r\n"
kind: ConfigMap
metadata:
  name: cloud-first-server-configmap
  namespace: cloud-demo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud-first-server
  namespace: cloud-demo
  labels:
    app: cloud-first-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloud-first-server
    spec:
      containers:
      - name: cloud-first-server
        image: 192.168.126.150:5000/cloud-demo/cloud-first-server:1.0
        #image: 192.168.126.150:5000/cloud-demo/cloud-eureka-kubernetes:1.0
        imagePullPolicy: IfNotPresent
        #args: ["--spring.config.location=application.properties"]
        ports:
        - containerPort: 10001
        volumeMounts:
        - name: cloud-first-server-config
          mountPath: /data/java/config
          #subPath: application.yml
      volumes:
      - name: cloud-first-server-config
        configMap:
          name: cloud-first-server-configmap
          items:
            - key: application.yml
              path: application.yml
